# This secret contains Docker registry credentials
# Since we're using stringData, all values below should be in plain text (not base64 encoded)
# Kubernetes will automatically handle the base64 encoding
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: devops
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "image-registry.openshift-image-registry.svc:5000": {
          "username": "<your-registry-username>",
          "password": "<your-registry-password>",
          "email": "<your-email>",
          # The auth field is optional as Kubernetes can generate it from username and password
          "auth": "<base64-encoded-auth>"
        }
      }
    }
