{{- if and .Values.sharedSecret.use (not (lookup "v1" "Secret" .Release.Namespace .Values.sharedSecret.name)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.sharedSecret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.sharedSecret.data }}
  {{ $key }}: {{ $value }}
  {{- end }}
{{- end }}