{{/* Shared Secret */}}
{{- if .Values.sharedSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: shared-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "octopilot.labels" . | nindent 4 }}
    app.kubernetes.io/component: shared-secret
type: Opaque
stringData:
  {{- range $key, $value := .Values.sharedSecret.data }}
  {{ $key }}: {{ $value }}
  {{- end }}
{{- end }}
